# Your database settings go here

defaults: &defaults
  adapter: mongodb
  url: localhost
  port: 27017
  # name: susana

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
